### ISSUE TITLE
Добавить лицензию к софту

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#1]
Думаю, стоит добавить лицензию, MIT или GPL3.0 покатят)

**Comment by lilSpeedwagon** [comment]
А для чего это нужно?

**Comment by KaiL4eK** [comment]
Не лишним будет уверенность в том, что твой код защищен) Принципиально ситуаций споров о правах не наблюдалось, но на всякий, скажем так)

**Comment by lilSpeedwagon** [comment]
Добавил GPLv3
