### ISSUE TITLE
Установка порта по-умолчанию

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#11]
Исключать возможность установки порта не стоит, по надо установить дефолтный не 80 (все таки какой-нибудь http сервак может висеть), а, например, 7777. Желательно после 1024, так как в лялихе для открытия порта нужны рутовые права.

**Comment by lilSpeedwagon** [comment]
Вернул настройку порта в интерфейс
По умолчанию установил 5556
