### ISSUE TITLE
Нужны ли функции `size()` в пакетах?

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#12]
Не заметил использования этих функций у пакетов, так ли они нужны. Очень мущает тот факт, что размеры заданы руками. Это зовется магическими числами. Лучше такие вещи выводить автоматически, что ты и делаешь, формируя массив байт и получая размер от него, что есть гут!

**Comment by lilSpeedwagon** [comment]
Я думаю лишними они не будут, пока не буду удалять
На расчет размера заменил на QByteArray::size()
