### ISSUE TITLE
[DataPackage] Может выпилить лишние поля?

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#14]
Подумывают над тем, чтобы выпилить поля типа данных, то есть зафиксировать размер пакета и, соответственно, передаваемые за раз данные

**Comment by KaiL4eK** [comment]
И на этот случай сделать два-три разных типа  пакета данных, так ведь данные о батарее нужны не сиюминутно, их можно и с частотой в 1 Гц передавать)

**Comment by lilSpeedwagon** [comment]
Убрал размер пакета данных, теперь он и правда не имеет смысла
Может все таки оставить все в одном пакете? Чтоб не создавать путаницы
