### ISSUE TITLE
[DataPackage] Лишняя реализация

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#15]
Реализации функции writeToBytes() как таковая не требуется от слова "совсем") Есть класс QDataStream, который отлично работает с преобразованиями данных в байты, что приводит к исключению собственных реализаций функци *ToBytes(). Думаю, имеет смыл пользовать функционал Qt, если уж используем таковой)

**Comment by KaiL4eK** [comment]
Это еще и облегчает жизнь, если надо реализовать двухсторонний "serialization/deserialization"

**Comment by lilSpeedwagon** [comment]
Пока что изменил так же в SetPackage, позже изменю остальные
