### ISSUE TITLE
[sv_client] Сканирование сети

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#16]
То ли друг друга не поняли, то ли реализация не та, сейчас выдает только представления интерфейсов локальной машины (планшета), пример:
127.0.0.1 - тут понятно
::1 - локальный IPv6
192.168.31.75 - сетевой планшета
То есть ты сканируешь не сеть, а свои интерфейсы)

**Comment by lilSpeedwagon** [comment]
Никаких готовых решений на Qt не могу найти
Судя по тому что пишут на форумах придется использовать API ОС и пинговать все адреса вручную, но и в этом есть минусы:
http://www.cyberforum.ru/qt/thread1407715.html
http://www.prog.org.ru/topic_31536_0.html
http://www.cyberforum.ru/qt/thread698038.html

**Comment by KaiL4eK** [comment]
255 потоков и сидим ждем результатов со всех, схема достаточно простая получается

**Comment by KaiL4eK** [comment]
Выводить список интерфейсов, добавить поле ввода данных ip, при выборе интерфейса переносить ip интерфейса для заполнения ip сервера
