### ISSUE TITLE
[Server] Сигнал подключения клиента

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#17]
Есть ли внешний сигнал, к которому можно подключиться, чтобы понимать, когда к нам подключился валидный клиент? Было бы очень полезно, но пока не вижу

**Comment by lilSpeedwagon** [comment]
Добавил signalNewConnection(qintptr descriptor)

**Comment by KaiL4eK** [comment]
Указывай плз в комментах к коммиту номер issue
