### ISSUE TITLE
[Client] Нагрузочное тестирование

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#18]
У меня есть новости и они не очень) Во-первых, при длительной работы начинаются фризы и жудкие тормоза. Смахивает на то, что он пытается рисовать все время все данные..) Вобщем, попробуй протетстить при постоянной отправке данных. 5Гц и через 3 минуты уже жуудкие задержки.
Кстати о задержках, надо будет прояснить способ отрисовки твоей оси времени, похоже он тормозит)

**Comment by KaiL4eK** [comment]
Вобщем, проведи тесты,и постарайся рещить проблему нагрузки, после решим траблы с рисовкой и частотой)

**Comment by lilSpeedwagon** [comment]
Увидел те же проблемы с фризами, отписался по ним в трелло
С графиками вроде тоже стало все в порядке
