### ISSUE TITLE
Организация API и функционала

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#2]
https://github.com/lilSpeedwagon/smart_vehicle_gui/blob/c5d97d7350ff184e107877fc18e7df0b0ebf2d7b/SmartVehicleServer/svserver.cpp#L19

Насколько я понял, сейчас для сервера надо передавать объект интерфейса, к которому сервак делает connect(), чтобы ловить сигналы. Может стоит сделать ряд открытых функций и открытых слотов и сигналов, чтобы любой мог просто создать объект сервака и пользовать функциями + подключаться к слотам/сигналам?

**Comment by lilSpeedwagon** [comment]
Обновил код
Функция добавления UI осталась, но слоты и сигналы для интерфейса открыты и ими можно пользоваться извне
Так же есть функции и сигналы/слоты для использования самого сервера
Все можно найти в serverAPI, ссылка на который в readme

**Comment by KaiL4eK** [comment]
Шикарно, закрывай, если считаешь, что завершено)
