### ISSUE TITLE
[SVClient][GUI] Реализация хранения данных на клиенте

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#21]

**Comment by KaiL4eK** [comment]
Перенести код из View в контроллер

**Comment by lilSpeedwagon** [comment]
В gui оставил только объявление Chart и Series для них
Получаю указатель на Series в Adapter и там при получении новых данных обрабатываю новые точки и сразу же их отображаю, таким образом можно убрать настройку частоты отображения данных
(оставить можно, если на мобильных устройствах нагрузка окажется слишком большой)
