### ISSUE TITLE
[Server]: Разделить сервер на графическое приложение и библиотеку передачи

### ISSUE THREAD

**Issue by KaiL4eK** [lilSpeedwagon/smart_vehicle_gui#8]
Так как графика является тестовой, то имеет смысл сделать графику тестовым приложением, которое использует библиотеку. В библиотеке должна содержаться логика соединения и передачи данных.

**Comment by lilSpeedwagon** [comment]
Обязательно ли делать целую библиотеку?
Ведь графика и серверная логика и так разделены на разные модули и сервер может работать без графики

**Comment by KaiL4eK** [comment]
Если ты считаешь, что вся логика так и останется в двух файлах при возможном расширении, тогда оставляй, как есть, но нужен тогда список файлов и заголовочных файлов, к которым надо линковаться, чтобы получить работоспособную логику без GUI

**Comment by lilSpeedwagon** [comment]
Хорошо, может я тогда добавлю этот список в документ с API
